version: '3.8'

services:
  download-excel-app:
    image: faizinahsan/download-excel-app:latest
    container_name: download-excel-app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=myAwEsOm3pa55@w0rd
      - DB_NAME=excel_db
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=myAwEsOm3pa55@w0rd
      - POSTGRES_DB=excel_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
